In [3]:
import pandas as pd
import numpy as np

In [ ]:
'''
01 O sistema exportou os pedidos sem calcular o valor total de cada um. 
Corrija isso no DataFrame antes de iniciar qualquer análise.

'''

df = pd.read_csv('pedidos_narashop.csv', sep=';')
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3
...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18

In [48]:
df.columns

Index(['pedido_id', 'vendedor', 'categoria', 'produto', 'status_pedido',
       'quantidade', 'valor_unitario', 'prazo_entrega_dias'],
      dtype='str')

In [51]:
df['valor_total'] = df['quantidade'] * df['valor_unitario']
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_total
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12,490.05
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4,87.67
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
...,...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5,665.08
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18,197.10

In [ ]:
'''
02 O gerente quer saber quais categorias geraram mais receita. 
Apresente o faturamento total por categoria, do maior para o menor.

'''

In [ ]:
'''
03 A diretoria precisa de um recorte para auditoria: pedidos com status 
'Entregue' e valor total acima de R$ 500.

'''

In [ ]:
'''
04 O diretor de operações quer identificar extremos no mix de produtos. 
Use Q1 e Q3 como corte: quais produtos estão no grupo dos 25% que 
mais faturam e no grupo dos 25% que menos faturam?

'''

In [ ]:
'''
05 O diretor de vendas suspeita de desigualdade entre vendedores. 
Aplique a mesma lógica de Q1 e Q3 ao faturamento por vendedor e 
identifique os dois grupos extremos.

'''

In [ ]:
'''
06
O gerente afirma que 'o ticket médio da NaraShop é de R$ 800'. 
Verifique. A média é confiável para representar o valor típico de um 
pedido? Calcule a distância e apresente uma resposta fundamentada.

'''